version: "3"

services:

    shopware6-latest:
      image: dockware/dev:latest
      container_name: shopware6-latest
      ports:
         - "80:80"
         - "3306:3306"
         - "2222:22"
         - "8888:8888"
         - "9999:9999"
      volumes:
         - "dw_latest-db_volume-sw:/var/lib/mysql"
         - "dw_latest-shop_volume-sw:/var/www/html"

#         - ".:/var/www/html" # mount bind

#         - "heiko_db_volume-sw:/var/lib/mysql"
#         - "heiko_shop_volume-sw:/var/www/html"
      networks:
         - web
      environment:
         - XDEBUG_ENABLED=1
volumes:
  dw_latest-db_volume-sw:
    driver: local
  dw_latest-shop_volume-sw:
    driver: local

#  heiko_db_volume-sw:
#    external: true
#  heiko_shop_volume-sw:
#    external: true

networks:
  web:
    external: false
